name: Update Semver

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
